# Generated by Django 4.2.23 on 2025-07-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='frozen_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
